// Writes src/lib/admin/tutorial-steps.ts from each video's timeline, using the same caption
// timing compose.cjs burns into the video, so the page's step list and the picture agree.
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const REPO = path.resolve(__dirname, "../..");
const INTRO = 3.4;
const MAP = {
  "01-add-a-listing": "add-a-listing",
  "02-log-an-issue": "log-a-change",
  "03-reply-to-enquiries": "reply-to-an-enquiry",
  "04-write-a-blog-post": "write-a-journal-post",
};

// The closing card of each video, so its text has an HTML twin too (see compose.cjs).
const OUTRO = {
  "add-a-listing": { title: "Your listing is the advert", line: "The title becomes its permanent web address, the first photo leads the card and the gallery, and the tagline and description turn someone browsing into a viewing. A few extra minutes on the words and pictures does more than any amount of promotion afterwards." },
  "log-a-change": { title: "Now try it yourself", line: "On a computer, press Try it now. A walkthrough guides you on the real screen, step by step." },
  "reply-to-an-enquiry": { title: "Now try it yourself", line: "Press Try it now. A walkthrough guides you on the real screen, step by step." },
  "write-a-journal-post": { title: "Now try it yourself", line: "On a computer, press Try it now. A walkthrough guides you on the real screen, step by step." },
};

// Content hash per file: a re-render changes the URL, so no cache can serve the old one.
const version = (rel) => crypto.createHash("sha1").update(fs.readFileSync(path.join(REPO, "public", rel))).digest("hex").slice(0, 10);

const out = {};
const media = {};
for (const [dir, id] of Object.entries(MAP)) {
  const t = JSON.parse(fs.readFileSync(path.join(REPO, "videos", dir, "timeline.json"), "utf8"));
  out[id] = t.captions.map((c, i, all) => {
    const next = all[i + 1];
    const end = next ? Math.min(c.end, next.start - 0.3) : Math.min(c.end, t.footageDuration - 0.2);
    return { at: +(INTRO + c.start).toFixed(1), until: +(INTRO + end).toFixed(1), title: c.title, line: c.line };
  });
  const outroAt = +(INTRO + t.footageDuration - 0.4).toFixed(1);
  const total = +(outroAt + (id === "add-a-listing" ? 11.5 : 5)).toFixed(1);
  out[id].push({ at: outroAt, until: total, ...OUTRO[id] });
  media[id] = { video: `/tutorials/${id}.mp4?v=${version(`tutorials/${id}.mp4`)}`, poster: `/tutorials/${id}.jpg?v=${version(`tutorials/${id}.jpg`)}` };
}

const lines = [
  "// Generated by videos/_tools/steps.cjs from videos/*/timeline.json. Times are seconds into",
  "// public/tutorials/<id>.mp4 and match the captions burned into each video.",
  'import type { TutorialId } from "@avhomes/contracts";',
  "",
  "export interface TutorialStep {",
  "  at: number;",
  "  until: number;",
  "  title: string;",
  "  line: string;",
  "}",
  "",
  "export const TUTORIAL_STEPS: Record<TutorialId, readonly TutorialStep[]> = {",
];
for (const [id, steps] of Object.entries(out)) {
  lines.push(`  "${id}": [`);
  for (const s of steps) lines.push(`    { at: ${s.at}, until: ${s.until}, title: ${JSON.stringify(s.title)}, line: ${JSON.stringify(s.line)} },`);
  lines.push("  ],");
}
lines.push("};", "");
lines.push("/** Versioned URLs for public/tutorials/<id>.{mp4,jpg}; the query is a content hash. */");
lines.push("export const TUTORIAL_MEDIA: Record<TutorialId, { video: string; poster: string }> = {");
for (const [id, m] of Object.entries(media)) lines.push(`  "${id}": { video: "${m.video}", poster: "${m.poster}" },`);
lines.push("};", "");
fs.writeFileSync(path.join(REPO, "src/lib/admin/tutorial-steps.ts"), lines.join("\n"));
console.log(Object.entries(out).map(([k, v]) => `${k}: ${v.length} steps`).join(", "));
