// Generated by videos/_tools/steps.cjs from videos/*/timeline.json. Times are seconds into
// public/tutorials/<id>.mp4 and match the captions burned into each video.
import type { TutorialId } from "@avhomes/contracts";

export interface TutorialStep {
  at: number;
  until: number;
  title: string;
  line: string;
}

export const TUTORIAL_STEPS: Record<TutorialId, readonly TutorialStep[]> = {
  "add-a-listing": [
    { at: 3.5, until: 6.9, title: "Listings, then New listing", line: "Every property lives here, drafts included." },
    { at: 7.2, until: 13.9, title: "Name it first", line: "This title becomes the web address when you publish." },
    { at: 14.2, until: 22.6, title: "Write it like an advert", line: "The tagline shows on every card. The description sells the viewing." },
    { at: 24.1, until: 28, title: "Sale or rent, then the price", line: "Pick the type and set the asking price in naira." },
    { at: 28.3, until: 35.2, title: "Where it is", line: "City, area and street address. Buyers search by all three." },
    { at: 35.5, until: 42.7, title: "Rooms and amenities", line: "Tap a suggestion, or type your own and press Enter." },
    { at: 43, until: 53.3, title: "Photos from the library", line: "The first one leads the listing card and the gallery." },
    { at: 53.6, until: 56.7, title: "Save your changes", line: "Nothing is public while it is a draft." },
    { at: 57, until: 59.6, title: "Publish", line: "It goes live with a permanent web address." },
    { at: 59.9, until: 70.2, title: "Live on the site", line: "Exactly what you wrote, with your photos and your price." },
    { at: 70.5, until: 82, title: "Rent works the same way", line: "Choose Rent and set the period: per night, month or year." },
    { at: 81.8, until: 93.3, title: "Your listing is the advert", line: "The title becomes its permanent web address, the first photo leads the card and the gallery, and the tagline and description turn someone browsing into a viewing. A few extra minutes on the words and pictures does more than any amount of promotion afterwards." },
  ],
  "log-a-change": [
    { at: 3.5, until: 9.3, title: "Customize, from the menu", line: "It opens the live site, exactly as visitors see it." },
    { at: 9.6, until: 16.2, title: "Mark up, then scroll to it", line: "Find the part of the page you want changed." },
    { at: 16.5, until: 19.5, title: "Freeze this screen", line: "It takes a picture of exactly what you are looking at." },
    { at: 19.8, until: 23.8, title: "Frame what you mean", line: "Circle, arrow, box or pen. Use as many as you need." },
    { at: 24.1, until: 30.1, title: "Say what should be different", line: "One clear sentence saves the developer a guess." },
    { at: 30.4, until: 37.3, title: "Saved for the developer", line: "They can mark it In progress or Done, and reply in the thread." },
    { at: 37.1, until: 42.1, title: "Now try it yourself", line: "On a computer, press Try it now. A walkthrough guides you on the real screen, step by step." },
  ],
  "reply-to-an-enquiry": [
    { at: 3.5, until: 7.9, title: "New enquiries come first", line: "The inbox opens on the ones nobody has answered." },
    { at: 8.2, until: 11.6, title: "Read what they asked", line: "Their message, their contact details and the listing they were on." },
    { at: 11.9, until: 21.8, title: "Answer, then offer a next step", line: "Shift+Enter adds a line. Enter sends." },
    { at: 22.1, until: 27.5, title: "They see it straight away", line: "In the chat on the site, and the whole thread by email." },
    { at: 27.8, until: 31.2, title: "Replying moves it to Open", line: "So the team can see it is being handled." },
    { at: 31.5, until: 34, title: "One fewer waiting", line: "Work down the New tab until it is empty." },
    { at: 33.8, until: 38.8, title: "Now try it yourself", line: "Press Try it now. A walkthrough guides you on the real screen, step by step." },
  ],
  "write-a-journal-post": [
    { at: 3.6, until: 10.4, title: "Journal, then New post", line: "A draft opens in the quick editor." },
    { at: 10.7, until: 28.1, title: "The details first", line: "Title, subtitle and a short excerpt. They show in search and on the card." },
    { at: 28.4, until: 40, title: "A cover photo, with alt text", line: "Describe the picture. Search engines and screen readers rely on it." },
    { at: 40.3, until: 46.2, title: "Save, then the advanced editor", line: "The full page writing studio, with your details carried over." },
    { at: 46.5, until: 57.5, title: "Write the body", line: "Type ## for a heading and 1. for a numbered list." },
    { at: 57.8, until: 61.9, title: "Publish", line: "It checks for anything missing first, then goes live." },
    { at: 62.1, until: 72.1, title: "Live on the site", line: "Under Insights, with your cover, subtitle and byline." },
    { at: 71.9, until: 76.9, title: "Now try it yourself", line: "On a computer, press Try it now. A walkthrough guides you on the real screen, step by step." },
  ],
};

/** Versioned URLs for public/tutorials/<id>.{mp4,jpg}; the query is a content hash. */
export const TUTORIAL_MEDIA: Record<TutorialId, { video: string; poster: string }> = {
  "add-a-listing": { video: "/tutorials/add-a-listing.mp4?v=14199a0fcb", poster: "/tutorials/add-a-listing.jpg?v=47631642ce" },
  "log-a-change": { video: "/tutorials/log-a-change.mp4?v=7d7416c399", poster: "/tutorials/log-a-change.jpg?v=d0a69b5205" },
  "reply-to-an-enquiry": { video: "/tutorials/reply-to-an-enquiry.mp4?v=27444d516e", poster: "/tutorials/reply-to-an-enquiry.jpg?v=901fc8a017" },
  "write-a-journal-post": { video: "/tutorials/write-a-journal-post.mp4?v=6768705bd7", poster: "/tutorials/write-a-journal-post.jpg?v=e6ebe28973" },
};
